


<!DOCTYPE html>
<html id="htmlId">
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=windows-1252"> 
  <title>Coverage Report > UsuarioControllerTest</title>
  <style type="text/css">
    @import "../../css/coverage.css";
    @import "../../css/idea.min.css";
  </style>
  <script type="text/javascript" src="../../js/highlight.min.js"></script>
  <script type="text/javascript" src="../../js/highlightjs-line-numbers.min.js"></script>
</head>

<body>
<div class="content">
<div class="breadCrumbs">
Current scope:     <a href="../../index.html">all classes</a>
    <span class="separator">|</span>
    <a href="../index.html">com.pagueibaratoapi.pagueibaratoapi.unit</a>
</div>

<h1>Coverage Summary for Class: UsuarioControllerTest (com.pagueibaratoapi.pagueibaratoapi.unit)</h1>

<table class="coverageStats">
<tr>
  <th class="name">Class</th>
<th class="coverageStat 
">
  Class, %
</th>
<th class="coverageStat 
">
  Method, %
</th>
<th class="coverageStat 
">
  Line, %
</th>
</tr>
<tr>
  <td class="name">UsuarioControllerTest</td>
<td class="coverageStat">
  <span class="percent">
    100%
  </span>
  <span class="absValue">
    (1/1)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    100%
  </span>
  <span class="absValue">
    (35/35)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    89,4%
  </span>
  <span class="absValue">
    (237/265)
  </span>
</td>
</tr>

</table>

<br/>
<br/>


<pre>
<code class="sourceCode" id="sourceCode">&nbsp;package com.pagueibaratoapi.pagueibaratoapi.unit;
&nbsp;
&nbsp;import static org.junit.Assert.assertEquals;
&nbsp;import static org.junit.Assert.assertNotNull;
&nbsp;import static org.junit.jupiter.api.Assertions.assertTrue;
&nbsp;import static org.mockito.ArgumentMatchers.any;
&nbsp;import static org.mockito.ArgumentMatchers.anyInt;
&nbsp;import static org.mockito.ArgumentMatchers.anyString;
&nbsp;import static org.mockito.Mockito.doThrow;
&nbsp;import static org.mockito.Mockito.verify;
&nbsp;import static org.mockito.Mockito.when;
&nbsp;
&nbsp;import java.util.ArrayList;
&nbsp;import java.util.List;
&nbsp;import java.util.Optional;
&nbsp;
&nbsp;import org.junit.Before;
&nbsp;import org.junit.Test;
&nbsp;import org.mockito.InjectMocks;
&nbsp;import org.mockito.Mock;
&nbsp;import org.mockito.MockitoAnnotations;
&nbsp;import org.springframework.dao.DataIntegrityViolationException;
&nbsp;import org.springframework.web.server.ResponseStatusException;
&nbsp;
&nbsp;import com.pagueibaratoapi.controllers.UsuarioController;
&nbsp;import com.pagueibaratoapi.models.requests.Usuario;
&nbsp;import com.pagueibaratoapi.models.responses.ResponseUsuario;
&nbsp;import com.pagueibaratoapi.pagueibaratoapi.PagueiBaratoApiApplicationTests;
&nbsp;import com.pagueibaratoapi.repository.UsuarioRepository;
&nbsp;
&nbsp;
&nbsp;
<b class="fc">&nbsp;public class UsuarioControllerTest extends PagueiBaratoApiApplicationTests {</b>
&nbsp;
&nbsp;    @InjectMocks
&nbsp;    private UsuarioController usuarioController;
&nbsp;
&nbsp;    @Mock
&nbsp;    private UsuarioRepository usuarioRepository;
&nbsp;
&nbsp;    @Mock
&nbsp;    private Optional&lt;Usuario&gt; optionalUsuario;
&nbsp;
&nbsp;    private Usuario usuario;
&nbsp;
&nbsp;    private List&lt;Usuario&gt; usuarios;
&nbsp;
&nbsp;
&nbsp;
&nbsp;    @Before
&nbsp;    public void setUp() {
<b class="fc">&nbsp;        MockitoAnnotations.openMocks(this);</b>
&nbsp;
<b class="fc">&nbsp;        this.inicializarUsuario();</b>
&nbsp;    }
&nbsp;
&nbsp;    private void inicializarUsuario() {
<b class="fc">&nbsp;        usuario = new Usuario();</b>
&nbsp;
<b class="fc">&nbsp;        usuario.setNome(&quot;Usuário Teste&quot;);</b>
<b class="fc">&nbsp;        usuario.setEmail(&quot;fulano@email.com&quot;);</b>
<b class="fc">&nbsp;        usuario.setLogradouro(&quot;Rua Teste&quot;);</b>
<b class="fc">&nbsp;        usuario.setNumero(123);</b>
<b class="fc">&nbsp;        usuario.setComplemento(&quot;Casa&quot;);</b>
<b class="fc">&nbsp;        usuario.setBairro(&quot;Bairro Teste&quot;);</b>
<b class="fc">&nbsp;        usuario.setCidade(&quot;Cidade Teste&quot;);</b>
<b class="fc">&nbsp;        usuario.setUf(&quot;SP&quot;);</b>
<b class="fc">&nbsp;        usuario.setCep(&quot;12345-678&quot;);</b>
<b class="fc">&nbsp;        usuario.setSenha(&quot;123456UsuarioT3ST3!&quot;);</b>
&nbsp;
<b class="fc">&nbsp;        Usuario usuario2 = new Usuario();</b>
&nbsp;
<b class="fc">&nbsp;        usuario2.setNome(&quot;Usuário Teste 2&quot;);</b>
<b class="fc">&nbsp;        usuario2.setEmail(&quot;ciclano@email.com&quot;);</b>
<b class="fc">&nbsp;        usuario2.setLogradouro(&quot;Rua Teste 2&quot;);</b>
<b class="fc">&nbsp;        usuario2.setNumero(456);</b>
<b class="fc">&nbsp;        usuario2.setComplemento(&quot;Casa 2&quot;);</b>
<b class="fc">&nbsp;        usuario2.setBairro(&quot;Bairro Teste 2&quot;);</b>
<b class="fc">&nbsp;        usuario2.setCidade(&quot;Cidade Teste 2&quot;);</b>
<b class="fc">&nbsp;        usuario2.setUf(&quot;SP&quot;);</b>
<b class="fc">&nbsp;        usuario2.setCep(&quot;12345-678&quot;);</b>
<b class="fc">&nbsp;        usuario2.setSenha(&quot;123456UsuarioT3ST3!&quot;);</b>
&nbsp;
<b class="fc">&nbsp;        this.usuarios = List.of(usuario, usuario2);</b>
&nbsp;        
&nbsp;    }
&nbsp;
&nbsp;
&nbsp;
&nbsp;    /* --------------------------  CRIAÇÃO DE USUÁRIO  -------------------------- */
&nbsp;
&nbsp;    @Test
&nbsp;    public void criarUsuarioComSucesso() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        ResponseUsuario response = usuarioController.criar(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        assertEquals(usuario.getNome(), response.getNome());</b>
<b class="fc">&nbsp;        assertEquals(usuario.getEmail(), response.getEmail());</b>
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void criarUsuarioComEmailExistente() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(usuario);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.criar(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        } catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(409, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;email_em_uso&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void criarUsuarioComDadosInvalidos() throws Exception {
&nbsp;
<b class="fc">&nbsp;        usuario.setSenha(&quot;123456&quot;);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.criar(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        } catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(400, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;senha_invalido&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void criarUsuarioComExcecaoDataViolation() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenThrow(new DataIntegrityViolationException(&quot;&quot;));</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.criar(usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_insercao&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void criarUsuarioComExcecaoIllegalArgument() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenThrow(new IllegalArgumentException(&quot;&quot;));</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.criar(usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;java.lang.IllegalArgumentException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void criarUsuarioComExcecao() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenThrow(new RuntimeException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.criar(usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;RuntimeException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    /* -------------------------------------------------------------------------- */
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;    /* -----------------------  LEITURA DE USUÁRIO POR ID ----------------------- */
&nbsp;
&nbsp;    @Test
&nbsp;    public void lerUsuarioComSucesso() throws Exception {
&nbsp;
<b class="fc">&nbsp;        usuario.setId(1);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        ResponseUsuario responseUsuario = usuarioController.ler(1);</b>
&nbsp;
<b class="fc">&nbsp;        assertEquals(usuario.getId(), responseUsuario.getId());</b>
<b class="fc">&nbsp;        assertEquals(usuario.getNome(), responseUsuario.getNome());</b>
<b class="fc">&nbsp;        assertEquals(usuario.getEmail(), responseUsuario.getEmail());</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void lerUsuarioInexistente() throws Exception {
&nbsp;
<b class="fc">&nbsp;        usuario.setEmail(&quot;&quot;);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.ler(1);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(404, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;usuario_nao_encontrado&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void lerUsuarioComExcecao() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenThrow(new RuntimeException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.ler(1);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;RuntimeException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    /* -------------------------------------------------------------------------- */
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;    /* --------------------------  LISTAGEM DE USUÁRIOS ------------------------- */
&nbsp;
&nbsp;    @Test
&nbsp;    public void listarComSucesso() {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findAll()).thenReturn(usuarios);</b>
&nbsp;        
<b class="fc">&nbsp;        List&lt;ResponseUsuario&gt; responseUsuarios = usuarioController.listar();</b>
&nbsp;
<b class="fc">&nbsp;        assertNotNull(responseUsuarios);</b>
<b class="fc">&nbsp;        assertEquals(usuarios.get(0).getNome(), responseUsuarios.get(0).getNome());</b>
<b class="fc">&nbsp;        assertEquals(usuarios.get(0).getEmail(), responseUsuarios.get(0).getEmail());</b>
<b class="fc">&nbsp;        assertEquals(usuarios.get(1).getNome(), responseUsuarios.get(1).getNome());</b>
<b class="fc">&nbsp;        assertEquals(&quot;ciclano@email.com&quot;, responseUsuarios.get(1).getEmail());</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void listarComExcecaoNullPointer() {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findAll()).thenReturn(new ArrayList&lt;&gt;());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.listar();</b>
&nbsp;
&nbsp;        } 
<b class="nc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="nc">&nbsp;            assertEquals(404, e.getRawStatusCode());</b>
<b class="nc">&nbsp;            assertEquals(&quot;nao_encontrado&quot;, e.getReason());</b>
<b class="fc">&nbsp;        }</b>
&nbsp;        
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void listarComExcecaoUnsupportedOperation() {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findAll()).thenThrow(new UnsupportedOperationException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.listar();</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;UnsupportedOperationException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void listarComExcecao() {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findAll()).thenThrow(new RuntimeException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.listar();</b>
&nbsp;
&nbsp;        }
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause() instanceof RuntimeException);</b>
<b class="nc">&nbsp;        }</b>
&nbsp;    }
&nbsp;
&nbsp;    /* -------------------------------------------------------------------------- */
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;    /* --------------------------  EDIÇÃO DE USUÁRIOS  -------------------------- */
&nbsp;
&nbsp;    @Test
&nbsp;    public void editarUsuarioComSucesso() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;        
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenReturn(usuarios.get(1));</b>
&nbsp;
<b class="fc">&nbsp;        usuarios.get(1).setSenha(null);</b>
&nbsp;
<b class="fc">&nbsp;        ResponseUsuario responseUsuario = usuarioController.editar(1, usuarios.get(1));</b>
&nbsp;
<b class="fc">&nbsp;        assertEquals(usuarios.get(1).getNome(), responseUsuario.getNome());</b>
<b class="fc">&nbsp;        assertEquals(usuarios.get(1).getEmail(), responseUsuario.getEmail());</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void editarUsuarioComEmailExistente() throws Exception {
&nbsp;
<b class="fc">&nbsp;        usuario.setSenha(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(usuario);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.editar(1, usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(409, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;email_em_uso&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void editarUsuarioComDadosInvalidos() throws Exception {
&nbsp;        
<b class="fc">&nbsp;        usuario.setSenha(&quot;123&quot;);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.editar(1, usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(400, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;senha_invalido&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void editarUsuarioComExcecaoDataViolation() throws Exception {
&nbsp;
<b class="fc">&nbsp;        this.usuario.setSenha(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;        
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenThrow(new DataIntegrityViolationException(&quot;&quot;));</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.editar(1, usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_insercao&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void editarUsuarioComExcecaoIllegalArgument() throws Exception {
&nbsp;        
<b class="fc">&nbsp;        usuario.setSenha(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;        
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenThrow(new IllegalArgumentException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.editar(1, usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;java.lang.IllegalArgumentException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void editarUsuarioComExcecaoNoSuchElement() throws Exception {
&nbsp;
<b class="fc">&nbsp;        usuario.setSenha(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(Optional.empty());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.editar(1, usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(404, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;nao_encontrado&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;        
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void editarUsuarioComExcecao() throws Exception {
&nbsp;
<b class="fc">&nbsp;        this.usuario.setSenha(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenThrow(new RuntimeException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.editar(1, usuario);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;RuntimeException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    /* -------------------------------------------------------------------------- */
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;    /* ------------------------  ATUALIZAÇÃO DE USUÁRIOS  ----------------------- */
&nbsp;
&nbsp;    @Test
&nbsp;    public void atualizarUsuarioComSucesso() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        ResponseUsuario responseUsuario = usuarioController.atualizar(1, usuario);</b>
&nbsp;
<b class="fc">&nbsp;        assertEquals(usuario.getNome(), responseUsuario.getNome());</b>
<b class="fc">&nbsp;        assertEquals(usuario.getEmail(), responseUsuario.getEmail());</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void atualizarUsuarioComEmailExistente() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(usuario);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.atualizar(1, usuario);</b>
&nbsp;
&nbsp;        }
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(409, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;email_em_uso&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void atualizarUsuarioComExcecaoNoSuchElement() throws Exception {
&nbsp;
<b class="fc">&nbsp;        this.usuario.setEmail(&quot;&quot;);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(this.usuario);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.atualizar(1, this.usuarios.get(1));</b>
&nbsp;
&nbsp;        }
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(404, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;usuario_nao_encontrado&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void atualizarUsuarioComDadosInvalidos() throws Exception {
&nbsp;
<b class="fc">&nbsp;        usuario.setSenha(&quot;123456&quot;);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.atualizar(1, usuario);</b>
&nbsp;
&nbsp;        }
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(400, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;senha_invalido&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void atualizarUsuarioComExcecaoDataViolation() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenThrow(new DataIntegrityViolationException(&quot;&quot;));</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.atualizar(1, usuario);</b>
&nbsp;
<b class="fc">&nbsp;        } catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_insercao&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void atualizarUsuarioComExcecaoIllegalArgument() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenThrow(new IllegalArgumentException(&quot;&quot;));</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.atualizar(1, usuario);</b>
&nbsp;
&nbsp;        }
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;java.lang.IllegalArgumentException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void atualizarUsuarioComExcecao() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findByEmail(anyString())).thenReturn(null);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.save(any())).thenThrow(new RuntimeException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.atualizar(1, usuario);</b>
&nbsp;
&nbsp;        }
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;RuntimeException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    /* -------------------------------------------------------------------------- */
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;
&nbsp;    /* --------------------------  DELEÇÃO DE USUÁRIOS  ------------------------- */
&nbsp;
&nbsp;    @Test
&nbsp;    public void removerUsuarioComSucesso() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        Object response = usuarioController.remover(1);</b>
&nbsp;
<b class="fc">&nbsp;        assertNotNull(response);</b>
&nbsp;
<b class="fc">&nbsp;        verify(usuarioRepository).save(any());</b>
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void removerUsuarioInexistente() throws Exception {
&nbsp;
<b class="fc">&nbsp;        usuario.setEmail(&quot;&quot;);</b>
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.remover(1);</b>
&nbsp;
<b class="fc">&nbsp;        } catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(404, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;usuario_nao_encontrado&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void removerUsuarioComExcecaoDataViolation() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        doThrow(new DataIntegrityViolationException(&quot;&quot;)).when(usuarioRepository).save(any());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.remover(1);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_remocao&quot;, e.getReason());</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void removerUsuarioComExcecaoIllegalArgument() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenReturn(optionalUsuario);</b>
<b class="fc">&nbsp;        when(optionalUsuario.get()).thenReturn(usuario);</b>
&nbsp;
<b class="fc">&nbsp;        doThrow(new IllegalArgumentException(&quot;&quot;)).when(usuarioRepository).save(any());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.remover(1);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;java.lang.IllegalArgumentException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;
&nbsp;    @Test
&nbsp;    public void removerUsuarioComExcecao() throws Exception {
&nbsp;
<b class="fc">&nbsp;        when(usuarioRepository.findById(anyInt())).thenThrow(new RuntimeException());</b>
&nbsp;
&nbsp;        try {
&nbsp;
<b class="fc">&nbsp;            usuarioController.remover(1);</b>
&nbsp;
&nbsp;        } 
<b class="fc">&nbsp;        catch (ResponseStatusException e) {</b>
<b class="fc">&nbsp;            assertEquals(500, e.getRawStatusCode());</b>
<b class="fc">&nbsp;            assertEquals(&quot;erro_inesperado&quot;, e.getReason());</b>
<b class="fc">&nbsp;            assertTrue(e.getCause().toString().contains(&quot;RuntimeException&quot;));</b>
<b class="nc">&nbsp;        }</b>
&nbsp;
&nbsp;    }
&nbsp;    
&nbsp;    /* -------------------------------------------------------------------------- */
&nbsp;
&nbsp;}
</code>
</pre>
</div>

<script type="text/javascript">
(function() {
    var msie = false, msie9 = false;
    /*@cc_on
      msie = true;
      @if (@_jscript_version >= 9)
        msie9 = true;
      @end
    @*/

    if (!msie || msie && msie9) {
      hljs.highlightAll()
      hljs.initLineNumbersOnLoad();
    }
})();
</script>

<div class="footer">
    
    <div style="float:right;">generated on 2023-11-25 03:05</div>
</div>
</body>
</html>
